apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: releasehub
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - migrate.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
images:
  - name: releasehub-server
    newTag: latest
  - name: releasehub-web
    newTag: latest

