import { theme, type ThemeConfig } from 'antd'

import type { ResolvedTheme } from './ThemePreferenceProvider'

export const releaseHubSeedColors = {
  light: {
    primary: '#4f46e5',
    success: '#14845e',
    warning: '#a15c00',
    error: '#c73942',
    info: '#2563eb',
  },
  dark: {
    primary: '#818cf8',
    success: '#34d399',
    warning: '#f59e0b',
    error: '#fb7185',
    info: '#60a5fa',
  },
} as const

const semantic = {
  page: cssVariable('--rh-color-page'),
  surface: cssVariable('--rh-color-surface'),
  elevated: cssVariable('--rh-color-surface-elevated'),
  surfaceSoft: cssVariable('--rh-color-surface-soft'),
  border: cssVariable('--rh-color-border'),
  borderStrong: cssVariable('--rh-color-border-strong'),
  text: cssVariable('--rh-color-text-primary'),
  textSecondary: cssVariable('--rh-color-text-secondary'),
  textDisabled: cssVariable('--rh-color-text-disabled'),
  textInverse: cssVariable('--rh-color-text-inverse'),
  primary: cssVariable('--rh-color-primary'),
  primaryHover: cssVariable('--rh-color-primary-hover'),
  primaryPressed: cssVariable('--rh-color-primary-pressed'),
  primarySoft: cssVariable('--rh-color-primary-soft'),
  primaryContrast: cssVariable('--rh-color-primary-contrast'),
  secondary: cssVariable('--rh-color-secondary'),
  secondarySoft: cssVariable('--rh-color-secondary-soft'),
  tertiary: cssVariable('--rh-color-tertiary'),
  focusSoft: cssVariable('--rh-color-focus-soft'),
  overlay: cssVariable('--rh-color-overlay'),
  success: cssVariable('--rh-color-success'),
  successSoft: cssVariable('--rh-color-success-soft'),
  warning: cssVariable('--rh-color-warning'),
  warningSoft: cssVariable('--rh-color-warning-soft'),
  error: cssVariable('--rh-color-error'),
  errorSoft: cssVariable('--rh-color-error-soft'),
  info: cssVariable('--rh-color-info'),
  infoSoft: cssVariable('--rh-color-info-soft'),
  shadow: cssVariable('--rh-shadow-card'),
  shadowFloating: cssVariable('--rh-shadow-floating'),
} as const

export function createReleaseHubTheme(mode: ResolvedTheme): ThemeConfig {
  const seed = releaseHubSeedColors[mode]

  return {
    algorithm: mode === 'dark' ? theme.darkAlgorithm : theme.defaultAlgorithm,
    token: {
      borderRadius: 8,
      borderRadiusLG: 12,
      boxShadow: semantic.shadowFloating,
      boxShadowSecondary: semantic.shadow,
      colorBgBase: semantic.page,
      colorBgContainer: semantic.surface,
      colorBgElevated: semantic.elevated,
      colorBgLayout: semantic.page,
      colorBgMask: semantic.overlay,
      colorBorder: semantic.borderStrong,
      colorBorderSecondary: semantic.border,
      colorError: seed.error,
      colorErrorBg: semantic.errorSoft,
      colorErrorText: semantic.error,
      colorInfo: seed.info,
      colorInfoBg: semantic.infoSoft,
      colorInfoText: semantic.info,
      colorLink: semantic.primary,
      colorLinkActive: semantic.primaryPressed,
      colorLinkHover: semantic.primaryHover,
      colorPrimary: seed.primary,
      colorPrimaryActive: semantic.primaryPressed,
      colorPrimaryBg: semantic.primarySoft,
      colorPrimaryBgHover: semantic.primarySoft,
      colorPrimaryBorder: semantic.primary,
      colorPrimaryHover: semantic.primaryHover,
      colorSuccess: seed.success,
      colorSuccessBg: semantic.successSoft,
      colorSuccessText: semantic.success,
      colorText: semantic.text,
      colorTextDisabled: semantic.textDisabled,
      colorTextLightSolid: semantic.primaryContrast,
      colorTextPlaceholder: semantic.textDisabled,
      colorTextSecondary: semantic.textSecondary,
      colorWarning: seed.warning,
      colorWarningBg: semantic.warningSoft,
      colorWarningText: semantic.warning,
      colorFillSecondary: semantic.surfaceSoft,
      colorSplit: semantic.border,
      controlItemBgActive: semantic.primarySoft,
      controlItemBgHover: semantic.surfaceSoft,
      controlHeight: 36,
      controlHeightLG: 40,
      controlHeightSM: 28,
      controlOutline: semantic.focusSoft,
      fontFamily: 'Inter, "Noto Sans TC", "PingFang TC", system-ui, sans-serif',
      fontSize: 14,
      lineHeight: 1.5,
      motionDurationFast: '0.12s',
      motionDurationMid: '0.2s',
      motionDurationSlow: '0.3s',
    },
    components: {
      Button: {
        dangerShadow: 'none',
        defaultBg: semantic.elevated,
        defaultBorderColor: semantic.borderStrong,
        defaultColor: semantic.text,
        defaultHoverBg: semantic.surfaceSoft,
        defaultHoverBorderColor: semantic.primary,
        defaultHoverColor: semantic.primary,
        defaultShadow: 'none',
        primaryShadow: 'none',
      },
      Card: {
        headerBg: 'transparent',
      },
      Input: {
        activeBg: semantic.surface,
        activeBorderColor: semantic.primary,
        activeShadow: `0 0 0 2px ${semantic.focusSoft}`,
        addonBg: semantic.surfaceSoft,
        errorActiveShadow: `0 0 0 2px ${semantic.errorSoft}`,
        hoverBg: semantic.surface,
        hoverBorderColor: semantic.primaryHover,
        warningActiveShadow: `0 0 0 2px ${semantic.warningSoft}`,
      },
      Layout: {
        bodyBg: semantic.page,
        headerBg: semantic.surface,
        headerColor: semantic.text,
        siderBg: semantic.surface,
      },
      Menu: {
        darkItemBg: 'transparent',
        darkItemColor: semantic.textSecondary,
        darkItemHoverBg: semantic.primarySoft,
        darkItemHoverColor: semantic.text,
        darkItemSelectedBg: semantic.primarySoft,
        darkItemSelectedColor: semantic.primary,
        darkSubMenuItemBg: 'transparent',
        itemBg: 'transparent',
        itemColor: semantic.textSecondary,
        itemBorderRadius: 8,
        itemHeight: 40,
        itemHoverBg: semantic.surfaceSoft,
        itemHoverColor: semantic.text,
        itemMarginBlock: 2,
        itemMarginInline: 8,
        itemSelectedBg: semantic.primarySoft,
        itemSelectedColor: semantic.primary,
      },
      Modal: {
        contentBg: semantic.elevated,
        headerBg: semantic.elevated,
      },
      Select: {
        optionActiveBg: semantic.surfaceSoft,
        optionSelectedBg: semantic.primarySoft,
        selectorBg: semantic.surface,
      },
      Segmented: {
        itemColor: semantic.textSecondary,
        itemHoverBg: semantic.surfaceSoft,
        itemSelectedBg: semantic.elevated,
        itemSelectedColor: semantic.text,
        trackBg: semantic.surfaceSoft,
      },
      Table: {
        borderColor: semantic.border,
        cellPaddingBlock: 12,
        cellPaddingInline: 16,
        headerBg: semantic.elevated,
        headerColor: semantic.text,
        rowHoverBg: semantic.primarySoft,
        rowSelectedBg: semantic.primarySoft,
        rowSelectedHoverBg: semantic.primarySoft,
      },
    },
  }
}

function cssVariable(name: string): string {
  return `var(${name})`
}
